import "server-only";

import { acquire } from "@/lib/providers/limiter";
import { ProviderError } from "@/lib/providers/types";
import { num } from "@/lib/providers/http";
import type { OptionChain, OptionLeg } from "@/lib/analytics/options";
import type { Instrument } from "@/lib/market/universe";
import { yahooSymbolFor } from "@/lib/providers/yahoo";

/**
 * Option chains from Yahoo Finance.
 *
 * The options endpoint sits behind a cookie-plus-crumb handshake that the
 * plain chart endpoint does not require: fetch a Yahoo page to receive session
 * cookies, exchange those for a short-lived crumb, then send the crumb on
 * every options request. Without it the API returns `Unauthorized: Invalid
 * Crumb` no matter how the headers are set.
 *
 * The crumb is cached in-process and re-minted when it expires.
 *
 * ── On Indian coverage ────────────────────────────────────────────────────
 * This covers US listings and US indices. NSE index options are published by
 * the exchange but the endpoint requires a token generated by client-side
 * JavaScript, which a server cannot reproduce — so Indian chains need a broker
 * API with a login (Upstox, Angel One and Dhan all offer one free). The
 * analytics in `lib/analytics/options.ts` are provider-agnostic and will work
 * against that data unchanged when it is wired in.
 */

const ID = "yahoo-options";

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36";

let crumb: string | null = null;
let cookies: string | null = null;
let mintedAt = 0;
const CRUMB_TTL_MS = 25 * 60 * 1000;

async function mintCrumb(): Promise<void> {
  // Step one: any Yahoo property will issue the consent cookies.
  const seed = await fetch("https://fc.yahoo.com", {
    headers: { "User-Agent": UA, Accept: "text/html" },
    cache: "no-store",
    signal: AbortSignal.timeout(8000),
  }).catch(() => null);

  const jar = seed?.headers.getSetCookie?.() ?? [];
  cookies = jar.map((c) => c.split(";")[0]).filter(Boolean).join("; ") || null;
  if (!cookies) throw new ProviderError(ID, "could not obtain Yahoo session cookies", 403, true);

  // Step two: trade the cookies for a crumb.
  const res = await fetch("https://query1.finance.yahoo.com/v1/test/getcrumb", {
    headers: { "User-Agent": UA, Accept: "text/plain", Cookie: cookies },
    cache: "no-store",
    signal: AbortSignal.timeout(8000),
  });

  const value = (await res.text()).trim();
  // A blocked handshake returns an HTML page rather than an error status.
  if (!value || value.length > 32 || value.includes("<")) {
    throw new ProviderError(ID, "could not obtain a Yahoo crumb", 403, true);
  }

  crumb = value;
  mintedAt = Date.now();
}

async function ensureCrumb(): Promise<void> {
  if (crumb && Date.now() - mintedAt < CRUMB_TTL_MS) return;
  await mintCrumb();
}

interface RawLeg {
  strike?: number;
  lastPrice?: number;
  bid?: number;
  ask?: number;
  volume?: number;
  openInterest?: number;
  impliedVolatility?: number;
  inTheMoney?: boolean;
}

interface RawResult {
  underlyingSymbol?: string;
  expirationDates?: number[];
  quote?: { regularMarketPrice?: number; currency?: string };
  options?: { expirationDate?: number; calls?: RawLeg[]; puts?: RawLeg[] }[];
}

function normaliseLeg(raw: RawLeg): OptionLeg | null {
  const strike = num(raw.strike);
  if (strike == null) return null;
  return {
    strike,
    lastPrice: num(raw.lastPrice) ?? 0,
    bid: num(raw.bid),
    ask: num(raw.ask),
    volume: num(raw.volume) ?? 0,
    openInterest: num(raw.openInterest) ?? 0,
    /*
     * Yahoo returns placeholder implied volatilities for strikes with no real
     * two-sided market — 0.00001 for untraded ones, and near-zero values on
     * the front expiry where there is barely any time value left to imply
     * anything from. Anything under 1% annualised is not a market's opinion
     * about volatility, so it is discarded rather than averaged into a
     * headline figure that would read as 0.4%.
     */
    impliedVolatility: (() => {
      const iv = num(raw.impliedVolatility);
      return iv != null && iv > 0.01 ? iv : null;
    })(),
    inTheMoney: raw.inTheMoney === true,
  };
}

/**
 * Fetch one expiry's chain. Omitting `expiry` returns the nearest one, which
 * is what the page loads with.
 */
export async function fetchOptionChain(
  inst: Instrument,
  expiry?: number,
): Promise<OptionChain | null> {
  if (inst.region === "IN") {
    throw new ProviderError(
      ID,
      "Indian option chains require a broker API — the exchange endpoint needs a browser-generated token",
      501,
      false,
    );
  }

  await acquire("yahoo", 1, 1200);
  await ensureCrumb();

  const symbol = yahooSymbolFor(inst);
  if (!symbol) return null;

  const url = new URL(`https://query1.finance.yahoo.com/v7/finance/options/${encodeURIComponent(symbol)}`);
  url.searchParams.set("crumb", crumb!);
  if (expiry) url.searchParams.set("date", String(Math.floor(expiry / 1000)));

  const res = await fetch(url, {
    headers: { "User-Agent": UA, Accept: "application/json", Cookie: cookies ?? "" },
    cache: "no-store",
    signal: AbortSignal.timeout(10_000),
  });

  if (!res.ok) throw new ProviderError(ID, `HTTP ${res.status}`, res.status, true);

  const payload = (await res.json()) as {
    optionChain?: { result?: RawResult[] | null; error?: { description?: string } | null };
  };

  const error = payload.optionChain?.error;
  if (error) {
    // An expired crumb is the common case; drop it so the next call re-mints.
    crumb = null;
    throw new ProviderError(ID, error.description ?? "options unavailable", 401, true);
  }

  const result = payload.optionChain?.result?.[0];
  if (!result) return null;

  const slice = result.options?.[0];
  const spot = num(result.quote?.regularMarketPrice);
  if (!slice || spot == null) return null;

  const calls = (slice.calls ?? []).map(normaliseLeg).filter((l): l is OptionLeg => l !== null);
  const puts = (slice.puts ?? []).map(normaliseLeg).filter((l): l is OptionLeg => l !== null);
  if (calls.length === 0 && puts.length === 0) return null;

  return {
    symbol: inst.symbol,
    expiry: (slice.expirationDate ?? result.expirationDates?.[0] ?? 0) * 1000,
    expiries: (result.expirationDates ?? []).map((s) => s * 1000),
    spot,
    calls: calls.sort((a, b) => a.strike - b.strike),
    puts: puts.sort((a, b) => a.strike - b.strike),
    currency: result.quote?.currency ?? "USD",
  };
}
